BASH_LOGS="cd ../../opt/airflow/dags && mkdir -p entorno/logs"
BASH_ESCUDOS="cd ../../opt/airflow/dags && mkdir -p entorno/imagenes/escudos"
BASH_ENTRENADORES="cd ../../opt/airflow/dags && mkdir -p entorno/imagenes/entrenadores"
BASH_PRESIDENTES="cd ../../opt/airflow/dags && mkdir -p entorno/imagenes/presidentes"
BASH_ESTADIOS="cd ../../opt/airflow/dags && mkdir -p entorno/imagenes/estadios"
URL_ESCUDO="https://cdn.resfu.com/img_data/equipos/"
URL_ENTRENADOR="https://cdn.resfu.com/img_data/people/original/"
URL_PRESIDENTE="https://cdn.resfu.com/img_data/people/original/"
URL_ESTADIO="https://cdn.resfu.com/img_data/estadios/original_new/"
ESCUDOS="escudos"
ENTRENADORES="entrenadores"
PRESIDENTES="presidentes"
ESTADIOS="estadios"
EQUIPO_ID=369 # Atletico de Madrid. Numero del escudo realmente, no el equipo_id. La web crea asi la URL
TEMPORADA_INICIO=1921
MES_FIN_TEMPORADA=6